<?php

namespace Database\Seeders;

use App\Http\QuaverApi\QuaverApi;
use App\Models\QuaverMap;
use Exception;
use Illuminate\Database\Seeder;

class QuaverMapStaticSeeder extends Seeder
{
    public function run()
    {
        foreach ($this->maps as $map) {
            QuaverMap::create($map);
        }
    }

    private array $maps = [
        [
            "quaver_map_id" => 26635,
            "quaver_mapset_id" => 3425,
            "quaver_creator_id" => 1439,
            "creator_username" => "nylevolx",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "EVERGLOW",
            "title" => "LA DI DA",
            "difficulty_name" => "EVERGLOW FOREVER LET'S GO",
            "length" => 207585,
            "bpm" => 164.0,
            "difficulty_rating" => 30.69,
            "count_hitobject_normal" => 919,
            "count_hitobject_long" => 1281,
        ],
        [
            "quaver_map_id" => 26708,
            "quaver_mapset_id" => 3434,
            "quaver_creator_id" => 1907,
            "creator_username" => "Eclipse",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "sakuzyo",
            "title" => "Lost Memory",
            "difficulty_name" => "Amnesia",
            "length" => 246445,
            "bpm" => 190.0,
            "difficulty_rating" => 20.16,
            "count_hitobject_normal" => 2396,
            "count_hitobject_long" => 10,
        ],
        [
            "quaver_map_id" => 26796,
            "quaver_mapset_id" => 3443,
            "quaver_creator_id" => 2672,
            "creator_username" => "Noch Einen",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "Root",
            "title" => "The Story of You and Me",
            "difficulty_name" => "Our Story",
            "length" => 185194,
            "bpm" => 180.0,
            "difficulty_rating" => 16.37,
            "count_hitobject_normal" => 1507,
            "count_hitobject_long" => 570,
        ],
        [
            "quaver_map_id" => 26811,
            "quaver_mapset_id" => 3444,
            "quaver_creator_id" => 11006,
            "creator_username" => "Striiker",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Dance Gavin Dance",
            "title" => "Death Of A Strawberry",
            "difficulty_name" => "Indecision",
            "length" => 247874,
            "bpm" => 125.0,
            "difficulty_rating" => 14.74,
            "count_hitobject_normal" => 1671,
            "count_hitobject_long" => 140,
        ],
        [
            "quaver_map_id" => 26838,
            "quaver_mapset_id" => 3446,
            "quaver_creator_id" => 7889,
            "creator_username" => "Keilann",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "Amatsuki",
            "title" => "Kaishin no Ichigeki!",
            "difficulty_name" => "It's a Critical Hit!",
            "length" => 232814,
            "bpm" => 118.0,
            "difficulty_rating" => 14.04,
            "count_hitobject_normal" => 2070,
            "count_hitobject_long" => 367,
        ],
        [
            "quaver_map_id" => 26839,
            "quaver_mapset_id" => 3447,
            "quaver_creator_id" => 4891,
            "creator_username" => "Storn",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Twilight Force",
            "title" => "Thundersword",
            "difficulty_name" => "Magic Sword",
            "length" => 291159,
            "bpm" => 155.0,
            "difficulty_rating" => 24.28,
            "count_hitobject_normal" => 3223,
            "count_hitobject_long" => 86,
        ],
        [
            "quaver_map_id" => 26840,
            "quaver_mapset_id" => 3448,
            "quaver_creator_id" => 4891,
            "creator_username" => "Storn",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Sonata Arctica",
            "title" => "Take One Breath",
            "difficulty_name" => "Preorder Your Future Today",
            "length" => 254274,
            "bpm" => 60.0,
            "difficulty_rating" => 5.75,
            "count_hitobject_normal" => 1567,
            "count_hitobject_long" => 35,
        ],
        [
            "quaver_map_id" => 26842,
            "quaver_mapset_id" => 3449,
            "quaver_creator_id" => 4891,
            "creator_username" => "Storn",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Sonata Arctica",
            "title" => "Blood",
            "difficulty_name" => "Beauty and Fear",
            "length" => 341210,
            "bpm" => 76.0,
            "difficulty_rating" => 16.03,
            "count_hitobject_normal" => 2131,
            "count_hitobject_long" => 263,
        ],
        [
            "quaver_map_id" => 26843,
            "quaver_mapset_id" => 3450,
            "quaver_creator_id" => 4891,
            "creator_username" => "Storn",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Rhapsody Of Fire",
            "title" => "Reign Of Terror",
            "difficulty_name" => "Terror",
            "length" => 394486,
            "bpm" => 170.0,
            "difficulty_rating" => 20.73,
            "count_hitobject_normal" => 3326,
            "count_hitobject_long" => 575,
        ],
        [
            "quaver_map_id" => 26845,
            "quaver_mapset_id" => 3452,
            "quaver_creator_id" => 4891,
            "creator_username" => "Storn",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Sabaton",
            "title" => "Smoking Snakes",
            "difficulty_name" => "Drei Brasilianischen Helden",
            "length" => 189789,
            "bpm" => 154.0,
            "difficulty_rating" => 11.64,
            "count_hitobject_normal" => 1375,
            "count_hitobject_long" => 240,
        ],
        [
            "quaver_map_id" => 26862,
            "quaver_mapset_id" => 3458,
            "quaver_creator_id" => 25902,
            "creator_username" => "PyaKura",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "cosMo@BousouP",
            "title" => "Oceanus",
            "difficulty_name" => "Sailing out!",
            "length" => 220933,
            "bpm" => 196.0,
            "difficulty_rating" => 33.88,
            "count_hitobject_normal" => 3534,
            "count_hitobject_long" => 470,
        ],
        [
            "quaver_map_id" => 26910,
            "quaver_mapset_id" => 3464,
            "quaver_creator_id" => 11006,
            "creator_username" => "Striiker",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Dance Gavin Dance",
            "title" => "Son Of Robot",
            "difficulty_name" => "Contention",
            "length" => 228504,
            "bpm" => 218.0,
            "difficulty_rating" => 14.88,
            "count_hitobject_normal" => 1394,
            "count_hitobject_long" => 355,
        ],
        [
            "quaver_map_id" => 26932,
            "quaver_mapset_id" => 3451,
            "quaver_creator_id" => 4891,
            "creator_username" => "Storn",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Twilight Force",
            "title" => "Gates of Glory",
            "difficulty_name" => "Primo Victoria",
            "length" => 233078,
            "bpm" => 150.0,
            "difficulty_rating" => 18.41,
            "count_hitobject_normal" => 2308,
            "count_hitobject_long" => 110,
        ],
        [
            "quaver_map_id" => 27029,
            "quaver_mapset_id" => 2230,
            "quaver_creator_id" => 1439,
            "creator_username" => "nylevolx",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Dreamcatcher",
            "title" => "Scream",
            "difficulty_name" => "Devil Eyes Come",
            "length" => 202201,
            "bpm" => 138.0,
            "difficulty_rating" => 30.8,
            "count_hitobject_normal" => 462,
            "count_hitobject_long" => 1653,
        ],
        [
            "quaver_map_id" => 27034,
            "quaver_mapset_id" => 3478,
            "quaver_creator_id" => 1907,
            "creator_username" => "Eclipse",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Camellia",
            "title" => "Body F10ating in the Zero Gravity Space",
            "difficulty_name" => "Celestial Descent",
            "length" => 277462,
            "bpm" => 170.0,
            "difficulty_rating" => 21.9,
            "count_hitobject_normal" => 1996,
            "count_hitobject_long" => 843,
        ],
        [
            "quaver_map_id" => 27135,
            "quaver_mapset_id" => 3487,
            "quaver_creator_id" => 1439,
            "creator_username" => "nylevolx",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "MAMAMOO",
            "title" => "HIP",
            "difficulty_name" => "Kagtu!!",
            "length" => 195994,
            "bpm" => 138.0,
            "difficulty_rating" => 21.16,
            "count_hitobject_normal" => 848,
            "count_hitobject_long" => 1031,
        ],
        [
            "quaver_map_id" => 27175,
            "quaver_mapset_id" => 3490,
            "quaver_creator_id" => 8318,
            "creator_username" => "Razorflame",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "2MB",
            "title" => "Healing Vision ~Angelic mix~",
            "difficulty_name" => "Beginnner",
            "length" => 103161,
            "bpm" => 196.0,
            "difficulty_rating" => 0.73,
            "count_hitobject_normal" => 149,
            "count_hitobject_long" => 26,
        ],
        [
            "quaver_map_id" => 27176,
            "quaver_mapset_id" => 3490,
            "quaver_creator_id" => 8318,
            "creator_username" => "Razorflame",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "2MB",
            "title" => "Healing Vision ~Angelic mix~",
            "difficulty_name" => "Easy",
            "length" => 103161,
            "bpm" => 196.0,
            "difficulty_rating" => 2.02,
            "count_hitobject_normal" => 392,
            "count_hitobject_long" => 26,
        ],
        [
            "quaver_map_id" => 27177,
            "quaver_mapset_id" => 3490,
            "quaver_creator_id" => 8318,
            "creator_username" => "Razorflame",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "2MB",
            "title" => "Healing Vision ~Angelic mix~",
            "difficulty_name" => "Advanced",
            "length" => 103161,
            "bpm" => 196.0,
            "difficulty_rating" => 10.28,
            "count_hitobject_normal" => 618,
            "count_hitobject_long" => 26,
        ],
        [
            "quaver_map_id" => 27180,
            "quaver_mapset_id" => 3490,
            "quaver_creator_id" => 8318,
            "creator_username" => "Razorflame",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "2MB",
            "title" => "Healing Vision ~Angelic mix~",
            "difficulty_name" => "Hard",
            "length" => 103161,
            "bpm" => 196.0,
            "difficulty_rating" => 15.94,
            "count_hitobject_normal" => 739,
            "count_hitobject_long" => 30,
        ],
        [
            "quaver_map_id" => 27233,
            "quaver_mapset_id" => 3498,
            "quaver_creator_id" => 934,
            "creator_username" => "Plutes",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "TWICE",
            "title" => "MORE & MORE",
            "difficulty_name" => "4K I Wanna Have More",
            "length" => 198417,
            "bpm" => 107.0,
            "difficulty_rating" => 20.56,
            "count_hitobject_normal" => 780,
            "count_hitobject_long" => 1076,
        ],
        [
            "quaver_map_id" => 27234,
            "quaver_mapset_id" => 3498,
            "quaver_creator_id" => 934,
            "creator_username" => "Plutes",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "TWICE",
            "title" => "MORE & MORE",
            "difficulty_name" => "7K Reba's You're gonna say more",
            "length" => 198184,
            "bpm" => 107.0,
            "difficulty_rating" => 31.14,
            "count_hitobject_normal" => 1109,
            "count_hitobject_long" => 2196,
        ],
        [
            "quaver_map_id" => 27347,
            "quaver_mapset_id" => 3500,
            "quaver_creator_id" => 2672,
            "creator_username" => "Noch Einen",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "KOTOKO",
            "title" => "Loop-the-Loop (TV Size)",
            "difficulty_name" => "Easy",
            "length" => 100375,
            "bpm" => 153.0,
            "difficulty_rating" => 1.86,
            "count_hitobject_normal" => 221,
            "count_hitobject_long" => 40,
        ],
        [
            "quaver_map_id" => 27348,
            "quaver_mapset_id" => 3500,
            "quaver_creator_id" => 2672,
            "creator_username" => "Noch Einen",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "KOTOKO",
            "title" => "Loop-the-Loop (TV Size)",
            "difficulty_name" => "Normal",
            "length" => 100375,
            "bpm" => 153.0,
            "difficulty_rating" => 5.2,
            "count_hitobject_normal" => 243,
            "count_hitobject_long" => 178,
        ],
        [
            "quaver_map_id" => 27357,
            "quaver_mapset_id" => 3507,
            "quaver_creator_id" => 37679,
            "creator_username" => "AsymetricLine",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Camellia",
            "title" => "+ERABY+E CONNEC+10N",
            "difficulty_name" => "+RANSC0N+1NEN+AL 1N+ERNE+",
            "length" => 300820,
            "bpm" => 230.0,
            "difficulty_rating" => 30.56,
            "count_hitobject_normal" => 2792,
            "count_hitobject_long" => 1504,
        ],
        [
            "quaver_map_id" => 27386,
            "quaver_mapset_id" => 3514,
            "quaver_creator_id" => 11548,
            "creator_username" => "Div",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Calliope Mori",
            "title" => "Excuse My Rudeness, but Could You Please RIP? (t+pazolite Remix)",
            "difficulty_name" => "Do me a favor and die?",
            "length" => 171965,
            "bpm" => 260.0,
            "difficulty_rating" => 33.49,
            "count_hitobject_normal" => 2812,
            "count_hitobject_long" => 72,
        ],
        [
            "quaver_map_id" => 27387,
            "quaver_mapset_id" => 3515,
            "quaver_creator_id" => 656,
            "creator_username" => "fvrex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Takagi-san (CV: Takahashi Rie)",
            "title" => "Kimagure Romantic (TV Size)",
            "difficulty_name" => "Collab Normal",
            "length" => 88138,
            "bpm" => 170.0,
            "difficulty_rating" => 3.5,
            "count_hitobject_normal" => 287,
            "count_hitobject_long" => 120,
        ],
        [
            "quaver_map_id" => 27388,
            "quaver_mapset_id" => 3515,
            "quaver_creator_id" => 656,
            "creator_username" => "fvrex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Takagi-san (CV: Takahashi Rie)",
            "title" => "Kimagure Romantic (TV Size)",
            "difficulty_name" => "Door to my heart",
            "length" => 88138,
            "bpm" => 170.0,
            "difficulty_rating" => 10.81,
            "count_hitobject_normal" => 357,
            "count_hitobject_long" => 262,
        ],
        [
            "quaver_map_id" => 27389,
            "quaver_mapset_id" => 3515,
            "quaver_creator_id" => 656,
            "creator_username" => "fvrex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Takagi-san (CV: Takahashi Rie)",
            "title" => "Kimagure Romantic (TV Size)",
            "difficulty_name" => "Hytex's Hard",
            "length" => 88138,
            "bpm" => 170.0,
            "difficulty_rating" => 5.5,
            "count_hitobject_normal" => 447,
            "count_hitobject_long" => 106,
        ],
        [
            "quaver_map_id" => 27428,
            "quaver_mapset_id" => 3521,
            "quaver_creator_id" => 49817,
            "creator_username" => "neyoru",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "ZYTOKINE",
            "title" => "DESIRE DREAM feat. itori - FELT Remix",
            "difficulty_name" => "Insane Side A",
            "length" => 205835,
            "bpm" => 125.0,
            "difficulty_rating" => 16.32,
            "count_hitobject_normal" => 2133,
            "count_hitobject_long" => 0,
        ],
        [
            "quaver_map_id" => 27429,
            "quaver_mapset_id" => 3521,
            "quaver_creator_id" => 49817,
            "creator_username" => "neyoru",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "ZYTOKINE",
            "title" => "DESIRE DREAM feat. itori - FELT Remix",
            "difficulty_name" => "Insane Side B",
            "length" => 206315,
            "bpm" => 125.0,
            "difficulty_rating" => 10.79,
            "count_hitobject_normal" => 79,
            "count_hitobject_long" => 998,
        ],
        [
            "quaver_map_id" => 27430,
            "quaver_mapset_id" => 3521,
            "quaver_creator_id" => 49817,
            "creator_username" => "neyoru",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "ZYTOKINE",
            "title" => "DESIRE DREAM feat. itori - FELT Remix",
            "difficulty_name" => "Melancholia",
            "length" => 206315,
            "bpm" => 125.0,
            "difficulty_rating" => 21.39,
            "count_hitobject_normal" => 6,
            "count_hitobject_long" => 2070,
        ],
        [
            "quaver_map_id" => 27465,
            "quaver_mapset_id" => 2871,
            "quaver_creator_id" => 1084,
            "creator_username" => "Lolicon",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "Miraie & Milkoi",
            "title" => "The Place You Promised To Show Me",
            "difficulty_name" => "Who are you talking to?",
            "length" => 224306,
            "bpm" => 153.0,
            "difficulty_rating" => 11.8,
            "count_hitobject_normal" => 1076,
            "count_hitobject_long" => 408,
        ],
        [
            "quaver_map_id" => 27532,
            "quaver_mapset_id" => 3542,
            "quaver_creator_id" => 1069,
            "creator_username" => "Skibble",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Black Sun Empire",
            "title" => "Inpeak (Telekinesis Remix)",
            "difficulty_name" => "Distortion",
            "length" => 154577,
            "bpm" => 174.0,
            "difficulty_rating" => 31.48,
            "count_hitobject_normal" => 407,
            "count_hitobject_long" => 1476,
        ],
        [
            "quaver_map_id" => 27533,
            "quaver_mapset_id" => 3542,
            "quaver_creator_id" => 1069,
            "creator_username" => "Skibble",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Black Sun Empire",
            "title" => "Inpeak (Telekinesis Remix)",
            "difficulty_name" => "Insane",
            "length" => 154577,
            "bpm" => 174.0,
            "difficulty_rating" => 27.25,
            "count_hitobject_normal" => 1823,
            "count_hitobject_long" => 66,
        ],
        [
            "quaver_map_id" => 27593,
            "quaver_mapset_id" => 3548,
            "quaver_creator_id" => 2570,
            "creator_username" => "Vysion",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "Sta",
            "title" => "Hall of Mirrors",
            "difficulty_name" => "Mirage",
            "length" => 262957,
            "bpm" => 147.0,
            "difficulty_rating" => 11.95,
            "count_hitobject_normal" => 1483,
            "count_hitobject_long" => 173,
        ],
        [
            "quaver_map_id" => 27619,
            "quaver_mapset_id" => 3490,
            "quaver_creator_id" => 8318,
            "creator_username" => "Razorflame",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "2MB",
            "title" => "Healing Vision ~Angelic mix~",
            "difficulty_name" => "Normal",
            "length" => 103161,
            "bpm" => 196.0,
            "difficulty_rating" => 6.03,
            "count_hitobject_normal" => 566,
            "count_hitobject_long" => 26,
        ],
        [
            "quaver_map_id" => 27669,
            "quaver_mapset_id" => 3558,
            "quaver_creator_id" => 1555,
            "creator_username" => "MARISA",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "t+pazolite with siromaru",
            "title" => "Chambarising",
            "difficulty_name" => "Living Embers",
            "length" => 288442,
            "bpm" => 160.0,
            "difficulty_rating" => 33.88,
            "count_hitobject_normal" => 4189,
            "count_hitobject_long" => 79,
        ],
        [
            "quaver_map_id" => 27685,
            "quaver_mapset_id" => 3561,
            "quaver_creator_id" => 2672,
            "creator_username" => "Noch Einen",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "Strawberry Prince",
            "title" => "Strawberry Nightmare",
            "difficulty_name" => "Ichigo Yume",
            "length" => 273295,
            "bpm" => 102.5,
            "difficulty_rating" => 14.48,
            "count_hitobject_normal" => 1466,
            "count_hitobject_long" => 869,
        ],
        [
            "quaver_map_id" => 27706,
            "quaver_mapset_id" => 3566,
            "quaver_creator_id" => 1102,
            "creator_username" => "Sebaex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Nankumo",
            "title" => "DRAGONLADY (DRAGONDERAY)",
            "difficulty_name" => "Another",
            "length" => 89554,
            "bpm" => 150.0,
            "difficulty_rating" => 20.74,
            "count_hitobject_normal" => 1025,
            "count_hitobject_long" => 0,
        ],
        [
            "quaver_map_id" => 27707,
            "quaver_mapset_id" => 3566,
            "quaver_creator_id" => 1102,
            "creator_username" => "Sebaex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Nankumo",
            "title" => "DRAGONLADY (DRAGONDERAY)",
            "difficulty_name" => "Black Another",
            "length" => 89554,
            "bpm" => 150.0,
            "difficulty_rating" => 25.85,
            "count_hitobject_normal" => 1331,
            "count_hitobject_long" => 0,
        ],
        [
            "quaver_map_id" => 27708,
            "quaver_mapset_id" => 3566,
            "quaver_creator_id" => 1102,
            "creator_username" => "Sebaex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Nankumo",
            "title" => "DRAGONLADY (DRAGONDERAY)",
            "difficulty_name" => "Dragon",
            "length" => 89554,
            "bpm" => 150.0,
            "difficulty_rating" => 29.14,
            "count_hitobject_normal" => 1534,
            "count_hitobject_long" => 0,
        ],
        [
            "quaver_map_id" => 27709,
            "quaver_mapset_id" => 3566,
            "quaver_creator_id" => 1102,
            "creator_username" => "Sebaex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Nankumo",
            "title" => "DRAGONLADY (DRAGONDERAY)",
            "difficulty_name" => "Hyper",
            "length" => 89254,
            "bpm" => 150.0,
            "difficulty_rating" => 13.77,
            "count_hitobject_normal" => 726,
            "count_hitobject_long" => 0,
        ],
        [
            "quaver_map_id" => 27710,
            "quaver_mapset_id" => 3566,
            "quaver_creator_id" => 1102,
            "creator_username" => "Sebaex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Nankumo",
            "title" => "DRAGONLADY (DRAGONDERAY)",
            "difficulty_name" => "Easy",
            "length" => 89254,
            "bpm" => 150.0,
            "difficulty_rating" => 2.3,
            "count_hitobject_normal" => 350,
            "count_hitobject_long" => 3,
        ],
        [
            "quaver_map_id" => 27711,
            "quaver_mapset_id" => 3566,
            "quaver_creator_id" => 1102,
            "creator_username" => "Sebaex",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Nankumo",
            "title" => "DRAGONLADY (DRAGONDERAY)",
            "difficulty_name" => "Normal",
            "length" => 89254,
            "bpm" => 150.0,
            "difficulty_rating" => 6.62,
            "count_hitobject_normal" => 574,
            "count_hitobject_long" => 20,
        ],
        [
            "quaver_map_id" => 27722,
            "quaver_mapset_id" => 3569,
            "quaver_creator_id" => 6132,
            "creator_username" => "Ceciliya",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Tektheist",
            "title" => "Walk With Me",
            "difficulty_name" => "Requiem",
            "length" => 296691,
            "bpm" => 212.0,
            "difficulty_rating" => 31.18,
            "count_hitobject_normal" => 4474,
            "count_hitobject_long" => 151,
        ],
        [
            "quaver_map_id" => 27755,
            "quaver_mapset_id" => 3574,
            "quaver_creator_id" => 96,
            "creator_username" => "Leniane",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Camellia",
            "title" => "#1f1e33",
            "difficulty_name" => "Insane",
            "length" => 158111,
            "bpm" => 181.0,
            "difficulty_rating" => 23.15,
            "count_hitobject_normal" => 1339,
            "count_hitobject_long" => 578,
        ],
        [
            "quaver_map_id" => 27756,
            "quaver_mapset_id" => 3575,
            "quaver_creator_id" => 96,
            "creator_username" => "Leniane",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Camellia",
            "title" => "Fly Wit Me",
            "difficulty_name" => "Ascension",
            "length" => 279514,
            "bpm" => 174.0,
            "difficulty_rating" => 20.17,
            "count_hitobject_normal" => 1931,
            "count_hitobject_long" => 807,
        ],
        [
            "quaver_map_id" => 27759,
            "quaver_mapset_id" => 3577,
            "quaver_creator_id" => 7234,
            "creator_username" => "11Bit",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Helblinde",
            "title" => "Love is War",
            "difficulty_name" => "speaker",
            "length" => 229923,
            "bpm" => 200.0,
            "difficulty_rating" => 34.57,
            "count_hitobject_normal" => 3821,
            "count_hitobject_long" => 87,
        ],
        [
            "quaver_map_id" => 27763,
            "quaver_mapset_id" => 3579,
            "quaver_creator_id" => 7234,
            "creator_username" => "11Bit",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "UNDEAD CORPORATION",
            "title" => "The Empress",
            "difficulty_name" => "Extra Boss",
            "length" => 273489,
            "bpm" => 270.0,
            "difficulty_rating" => 40.65,
            "count_hitobject_normal" => 6240,
            "count_hitobject_long" => 52,
        ],
        [
            "quaver_map_id" => 27764,
            "quaver_mapset_id" => 3580,
            "quaver_creator_id" => 7234,
            "creator_username" => "11Bit",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "UNDEAD CORPORATION",
            "title" => "MEGALOMANIA",
            "difficulty_name" => "Last Boss",
            "length" => 271266,
            "bpm" => 270.0,
            "difficulty_rating" => 38.29,
            "count_hitobject_normal" => 6412,
            "count_hitobject_long" => 9,
        ],
        [
            "quaver_map_id" => 27766,
            "quaver_mapset_id" => 3582,
            "quaver_creator_id" => 7234,
            "creator_username" => "11Bit",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "UNDEAD CORPORATION",
            "title" => "and Say Good Bye...",
            "difficulty_name" => "Warrior",
            "length" => 232423,
            "bpm" => 260.0,
            "difficulty_rating" => 38.12,
            "count_hitobject_normal" => 5196,
            "count_hitobject_long" => 9,
        ],
        [
            "quaver_map_id" => 27767,
            "quaver_mapset_id" => 3583,
            "quaver_creator_id" => 7234,
            "creator_username" => "11Bit",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "TUYU",
            "title" => "Doro no Bunzai de Watashi dake no Taisetsu o Ubaouda nante",
            "difficulty_name" => "Fallen Angel",
            "length" => 189646,
            "bpm" => 225.0,
            "difficulty_rating" => 31.76,
            "count_hitobject_normal" => 2907,
            "count_hitobject_long" => 43,
        ],
        [
            "quaver_map_id" => 27772,
            "quaver_mapset_id" => 3586,
            "quaver_creator_id" => 2168,
            "creator_username" => "LongNotes",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "Christopher Larkin",
            "title" => "Lace",
            "difficulty_name" => "Pharloom",
            "length" => 159776,
            "bpm" => 153.0,
            "difficulty_rating" => 22.47,
            "count_hitobject_normal" => 2059,
            "count_hitobject_long" => 152,
        ],
        [
            "quaver_map_id" => 27823,
            "quaver_mapset_id" => 3595,
            "quaver_creator_id" => 486,
            "creator_username" => "BetaVN",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "ARForest",
            "title" => "The Last Page",
            "difficulty_name" => "Epilogue",
            "length" => 137691,
            "bpm" => 195.0,
            "difficulty_rating" => 38.39,
            "count_hitobject_normal" => 2729,
            "count_hitobject_long" => 48,
        ],
        [
            "quaver_map_id" => 27824,
            "quaver_mapset_id" => 3596,
            "quaver_creator_id" => 49817,
            "creator_username" => "neyoru",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "LV.4 mixed by Rems",
            "title" => "Across The Solar System",
            "difficulty_name" => "CODE-STAMINA (Marathon)",
            "length" => 3582104,
            "bpm" => 180.0,
            "difficulty_rating" => 31.9,
            "count_hitobject_normal" => 58860,
            "count_hitobject_long" => 93,
        ],
        [
            "quaver_map_id" => 27846,
            "quaver_mapset_id" => 3595,
            "quaver_creator_id" => 486,
            "creator_username" => "BetaVN",
            "game_mode" => 2,
            "ranked_status" => 2,
            "artist" => "ARForest",
            "title" => "The Last Page",
            "difficulty_name" => "Prelude",
            "length" => 137691,
            "bpm" => 195.0,
            "difficulty_rating" => 37.09,
            "count_hitobject_normal" => 2515,
            "count_hitobject_long" => 48,
        ],
        [
            "quaver_map_id" => 27916,
            "quaver_mapset_id" => 3607,
            "quaver_creator_id" => 349,
            "creator_username" => "Kroly",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Bossfight",
            "title" => "Charge",
            "difficulty_name" => "Archaic's Overpowered",
            "length" => 187807,
            "bpm" => 124.0,
            "difficulty_rating" => 29.23,
            "count_hitobject_normal" => 2509,
            "count_hitobject_long" => 85,
        ],
        [
            "quaver_map_id" => 27917,
            "quaver_mapset_id" => 3607,
            "quaver_creator_id" => 349,
            "creator_username" => "Kroly",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Bossfight",
            "title" => "Charge",
            "difficulty_name" => "Boosted",
            "length" => 187807,
            "bpm" => 124.0,
            "difficulty_rating" => 27.43,
            "count_hitobject_normal" => 2020,
            "count_hitobject_long" => 180,
        ],
        [
            "quaver_map_id" => 27918,
            "quaver_mapset_id" => 3608,
            "quaver_creator_id" => 349,
            "creator_username" => "Kroly",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Odaxelagnia",
            "title" => "Chocolate Discore",
            "difficulty_name" => "Sweetness Overload!",
            "length" => 172604,
            "bpm" => 162.83,
            "difficulty_rating" => 27.61,
            "count_hitobject_normal" => 2763,
            "count_hitobject_long" => 0,
        ],
        [
            "quaver_map_id" => 27922,
            "quaver_mapset_id" => 3609,
            "quaver_creator_id" => 349,
            "creator_username" => "Kroly",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Plazma feat. Nahoko",
            "title" => "Connect",
            "difficulty_name" => "Goddess",
            "length" => 282926,
            "bpm" => 180.0,
            "difficulty_rating" => 28.61,
            "count_hitobject_normal" => 4149,
            "count_hitobject_long" => 97,
        ],
        [
            "quaver_map_id" => 28050,
            "quaver_mapset_id" => 3620,
            "quaver_creator_id" => 455,
            "creator_username" => "Milky",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "aivi & surasshu",
            "title" => "Alone Together",
            "difficulty_name" => "Twilight",
            "length" => 47211,
            "bpm" => 102.0,
            "difficulty_rating" => 4.34,
            "count_hitobject_normal" => 184,
            "count_hitobject_long" => 63,
        ],
        [
            "quaver_map_id" => 28106,
            "quaver_mapset_id" => 3626,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Taku Inoue",
            "title" => "Our Night Out",
            "difficulty_name" => "Irreplaceable",
            "length" => 224705,
            "bpm" => 168.0,
            "difficulty_rating" => 22.41,
            "count_hitobject_normal" => 2093,
            "count_hitobject_long" => 249,
        ],
        [
            "quaver_map_id" => 28108,
            "quaver_mapset_id" => 3627,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "typeMARS",
            "title" => "Triumph & Regret",
            "difficulty_name" => "Hard",
            "length" => 123967,
            "bpm" => 175.0,
            "difficulty_rating" => 17.21,
            "count_hitobject_normal" => 1186,
            "count_hitobject_long" => 123,
        ],
        [
            "quaver_map_id" => 28110,
            "quaver_mapset_id" => 3627,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "typeMARS",
            "title" => "Triumph & Regret",
            "difficulty_name" => "Mega - Regret",
            "length" => 122596,
            "bpm" => 175.0,
            "difficulty_rating" => 27.31,
            "count_hitobject_normal" => 974,
            "count_hitobject_long" => 718,
        ],
        [
            "quaver_map_id" => 28111,
            "quaver_mapset_id" => 3627,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "typeMARS",
            "title" => "Triumph & Regret",
            "difficulty_name" => "Mega - Triumph",
            "length" => 122597,
            "bpm" => 175.0,
            "difficulty_rating" => 25.54,
            "count_hitobject_normal" => 1749,
            "count_hitobject_long" => 2,
        ],
        [
            "quaver_map_id" => 28112,
            "quaver_mapset_id" => 3627,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "typeMARS",
            "title" => "Triumph & Regret",
            "difficulty_name" => "Normal",
            "length" => 123967,
            "bpm" => 175.0,
            "difficulty_rating" => 6.71,
            "count_hitobject_normal" => 738,
            "count_hitobject_long" => 78,
        ],
        [
            "quaver_map_id" => 28114,
            "quaver_mapset_id" => 3629,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Taishi",
            "title" => "All For The Time",
            "difficulty_name" => "insane",
            "length" => 275505,
            "bpm" => 180.0,
            "difficulty_rating" => 12.32,
            "count_hitobject_normal" => 1316,
            "count_hitobject_long" => 218,
        ],
        [
            "quaver_map_id" => 28115,
            "quaver_mapset_id" => 3629,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Taishi",
            "title" => "All For The Time",
            "difficulty_name" => "time flies",
            "length" => 275506,
            "bpm" => 180.0,
            "difficulty_rating" => 17.96,
            "count_hitobject_normal" => 1514,
            "count_hitobject_long" => 270,
        ],
        [
            "quaver_map_id" => 28116,
            "quaver_mapset_id" => 3630,
            "quaver_creator_id" => 1661,
            "creator_username" => "AHHHHHHHHHHHHHH",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Baco",
            "title" => "PLASMA Cube",
            "difficulty_name" => "ENERgy",
            "length" => 383578,
            "bpm" => 155.0,
            "difficulty_rating" => 29.81,
            "count_hitobject_normal" => 5375,
            "count_hitobject_long" => 43,
        ],
        [
            "quaver_map_id" => 28233,
            "quaver_mapset_id" => 3645,
            "quaver_creator_id" => 1770,
            "creator_username" => "UnluckyCroco",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "Camellia",
            "title" => "chrono diver -fragment- (Camellia's \"crossroads of chrono\" remix)",
            "difficulty_name" => "Everlasting Dream",
            "length" => 313782,
            "bpm" => 149.0,
            "difficulty_rating" => 20.14,
            "count_hitobject_normal" => 1579,
            "count_hitobject_long" => 1094,
        ],
        [
            "quaver_map_id" => 28374,
            "quaver_mapset_id" => 3657,
            "quaver_creator_id" => 49817,
            "creator_username" => "neyoru",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "KopophobiA & SpaceChimp & MinDelve",
            "title" => "Naruto RMX",
            "difficulty_name" => "Tsukuyomi",
            "length" => 534536,
            "bpm" => 238.0,
            "difficulty_rating" => 37.22,
            "count_hitobject_normal" => 10931,
            "count_hitobject_long" => 7,
        ],
        [
            "quaver_map_id" => 70810,
            "quaver_mapset_id" => 3620,
            "quaver_creator_id" => 455,
            "creator_username" => "Plushu",
            "game_mode" => 1,
            "ranked_status" => 2,
            "artist" => "aivi & surasshu",
            "title" => "Alone Together",
            "difficulty_name" => "Alyca's Dusk",
            "length" => 47211,
            "bpm" => 102.0,
            "difficulty_rating" => 1.43,
            "count_hitobject_normal" => 66,
            "count_hitobject_long" => 65,
        ],
    ];
}
