version: '3.9'

networks:
    project_net:

services:
    server:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        container_name: '${APP_NAME}-server'
        ports:
            - '80:80'
            - '443:443'
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
            - ./docker/ssl:/etc/apache2/ssl
            - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
        networks:
            - project_net
